### ISSUE TITLE
rocm version-dev file not found

### ISSUE THREAD

**Issue by acxz** [rocm-arch/tensorflow-rocm#17]
```bash
INFO: Repository local_config_rocm instantiated at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/WORKSPACE:19:16: in <toplevel>
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/tensorflow/workspace.bzl:102:19: in tf_repositories
Repository rule rocm_configure defined at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl:794:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 775, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 534, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 388, column 30, in _get_rocm_config
		config = find_rocm_config(repository_ctx, find_rocm_config_script)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 366, column 41, in find_rocm_config
		exec_result = _exec_find_rocm_config(repository_ctx, script_path)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 362, column 19, in _exec_find_rocm_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_rocm//rocm': Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
ERROR: no such package '@local_config_rocm//rocm': Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
```

**Comment by acxz** [comment]
upstream issue: https://github.com/tensorflow/tensorflow/issues/45733

**Comment by acxz** [comment]
resolved with above mentioned PR
