### ISSUE TITLE
Invalid escape sequence

### ISSUE THREAD

**Issue by jlo62** [rocm-arch/tensorflow-rocm#71]
```
==> Making package: tensorflow-rocm 2.17.0-1 (Sat 02 Nov 2024 08:25:49 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found tensorflow-rocm-2.17.0.tar.gz
  -> Found tensorflow-2.16.1-python-distutils-removal.patch
  -> Found tensorflow-numpy2.patch
  -> Found bazel_nojdk-6.5.0-linux-x86_64
  -> Found escape.patch
==> Validating source files with sha512sums...
    tensorflow-rocm-2.17.0.tar.gz ... Passed
    tensorflow-2.16.1-python-distutils-removal.patch ... Passed
    tensorflow-numpy2.patch ... Passed
    bazel_nojdk-6.5.0-linux-x86_64 ... Passed
    escape.patch ... Skipped
==> Extracting sources...
  -> Extracting tensorflow-rocm-2.17.0.tar.gz with bsdtar
  -> Extracting bazel_nojdk-6.5.0-linux-x86_64 with bsdtar
==> Starting prepare()...
bazel 6.5.0
patching file tensorflow/api_template.__init__.py
Hunk #2 succeeded at 96 (offset 2 lines).
patching file tensorflow/api_template_v1.__init__.py
patching file tensorflow/lite/python/convert.py
Hunk #3 succeeded at 411 (offset 9 lines).
/home/janluca/makepkg/clone/tensorflow-rocm/PKGBUILD: line 136: /opt/cuda/bin/nvcc: No such file or directory
sed: can't read /usr/include/cudnn_version.h: No such file or directory
==> Starting build()...
Building with rocm and without non-x86-64 optimizations
You have bazel 6.5.0 installed.
You have Clang 18.1.8 installed.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [rocm, no_tfrt]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: option '--output_filter' was expanded to from both option '--config=short_logs' (source /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc) and option '--config=verbose_logs' (source command line options)
INFO: Reading 'startup' options from /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=105
INFO: Reading rc options for 'build' from /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3.12 --action_env PYTHON_LIB_PATH=/usr/lib/python3.12/site-packages --python_path=/usr/bin/python3.12 --define=with_xla_support=true --config=rocm --action_env CLANG_COMPILER_PATH=/usr/bin/clang-18 --repo_env=CC=/usr/bin/clang-18 --repo_env=BAZEL_COMPILER=/usr/bin/clang-18 --action_env TF_SYSTEM_LIBS=boringssl,curl,cython,gif,icu,libjpeg_turbo,nasm,png,zlib
INFO: Found applicable config definition build:short_logs in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:rocm in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm_hipcc=true --define=tensorflow_mkldnn_contraction_kernel=0 --repo_env TF_NEED_ROCM=1 --config=no_tfrt
INFO: Found applicable config definition build:no_tfrt in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/ir,tensorflow/compiler/mlir/tfrt/ir/mlrt,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ifrt,tensorflow/compiler/mlir/tfrt/tests/mlrt,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/compiler/mlir/tfrt/transforms/mlrt,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/runtime_fallback/test,tensorflow/core/runtime_fallback/test/gpu,tensorflow/core/runtime_fallback/test/saved_model,tensorflow/core/runtime_fallback/test/testdata,tensorflow/core/tfrt/stubs,tensorflow/core/tfrt/tfrt_session,tensorflow/core/tfrt/mlrt,tensorflow/core/tfrt/mlrt/attribute,tensorflow/core/tfrt/mlrt/kernel,tensorflow/core/tfrt/mlrt/bytecode,tensorflow/core/tfrt/mlrt/interpreter,tensorflow/compiler/mlir/tfrt/translate/mlrt,tensorflow/compiler/mlir/tfrt/translate/mlrt/testdata,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils,tensorflow/core/tfrt/utils/debug,tensorflow/core/tfrt/saved_model/python,tensorflow/core/tfrt/graph_executor/python,tensorflow/core/tfrt/saved_model/utils
INFO: Found applicable config definition build:rocm in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm_hipcc=true --define=tensorflow_mkldnn_contraction_kernel=0 --repo_env TF_NEED_ROCM=1 --config=no_tfrt
INFO: Found applicable config definition build:no_tfrt in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/ir,tensorflow/compiler/mlir/tfrt/ir/mlrt,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ifrt,tensorflow/compiler/mlir/tfrt/tests/mlrt,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/compiler/mlir/tfrt/transforms/mlrt,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/runtime_fallback/test,tensorflow/core/runtime_fallback/test/gpu,tensorflow/core/runtime_fallback/test/saved_model,tensorflow/core/runtime_fallback/test/testdata,tensorflow/core/tfrt/stubs,tensorflow/core/tfrt/tfrt_session,tensorflow/core/tfrt/mlrt,tensorflow/core/tfrt/mlrt/attribute,tensorflow/core/tfrt/mlrt/kernel,tensorflow/core/tfrt/mlrt/bytecode,tensorflow/core/tfrt/mlrt/interpreter,tensorflow/compiler/mlir/tfrt/translate/mlrt,tensorflow/compiler/mlir/tfrt/translate/mlrt/testdata,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils,tensorflow/core/tfrt/utils/debug,tensorflow/core/tfrt/saved_model/python,tensorflow/core/tfrt/graph_executor/python,tensorflow/core/tfrt/saved_model/utils
INFO: Found applicable config definition build:verbose_logs in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --output_filter=
INFO: Found applicable config definition build:linux in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: The following configs were expanded more than once: [rocm, no_tfrt]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: option '--output_filter' was expanded to from both option '--config=short_logs' (source /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/.bazelrc) and option '--config=verbose_logs' (source command line options)
INFO: Repository local_config_rocm instantiated at:
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/WORKSPACE:95:14: in <toplevel>
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/tensorflow/workspace2.bzl:928:19: in workspace
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/tensorflow/workspace2.bzl:112:19: in _tf_toolchains
Repository rule rocm_configure defined at:
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl:846:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 823, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 555, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin)
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 406, column 41, in _get_rocm_config
		amdgpu_targets = _amdgpu_targets(repository_ctx, rocm_toolkit_path, bash_bin),
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 232, column 25, in _amdgpu_targets
		result = execute(repository_ctx, [bash_bin, "-c", cmd])
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
/opt/rocm/bin/rocm_agent_enumerator:95: SyntaxWarning: invalid escape sequence '\w'
  @staticVars(search_name=re.compile("gfx[0-9a-fA-F]+(:[-+:\w]+)?"))
/opt/rocm/bin/rocm_agent_enumerator:152: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(amdgcn-amd-amdhsa--gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:154: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:175: SyntaxWarning: invalid escape sequence '\w'
  target_search_term = re.compile("1002:\w+")
ERROR: /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/WORKSPACE:95:14: fetching rocm_configure rule //external:local_config_rocm: Traceback (most recent call last):
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 823, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 555, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin)
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 406, column 41, in _get_rocm_config
		amdgpu_targets = _amdgpu_targets(repository_ctx, rocm_toolkit_path, bash_bin),
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/gpus/rocm_configure.bzl", line 232, column 25, in _amdgpu_targets
		result = execute(repository_ctx, [bash_bin, "-c", cmd])
	File "/tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
/opt/rocm/bin/rocm_agent_enumerator:95: SyntaxWarning: invalid escape sequence '\w'
  @staticVars(search_name=re.compile("gfx[0-9a-fA-F]+(:[-+:\w]+)?"))
/opt/rocm/bin/rocm_agent_enumerator:152: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(amdgcn-amd-amdhsa--gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:154: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:175: SyntaxWarning: invalid escape sequence '\w'
  target_search_term = re.compile("1002:\w+")
INFO: Repository rules_proto instantiated at:
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/WORKSPACE:103:14: in <toplevel>
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/tensorflow/workspace0.bzl:114:17: in workspace
Repository rule http_archive defined at:
  /home/janluca/.cache/bazel/_bazel_janluca/604c7e0350e7b3b80f4666a83c15fa30/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository rules_cc instantiated at:
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/WORKSPACE:99:14: in <toplevel>
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/tensorflow/workspace1.bzl:34:14: in workspace
  /home/janluca/.cache/bazel/_bazel_janluca/604c7e0350e7b3b80f4666a83c15fa30/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:158:21: in grpc_deps
Repository rule http_archive defined at:
  /home/janluca/.cache/bazel/_bazel_janluca/604c7e0350e7b3b80f4666a83c15fa30/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository rules_java instantiated at:
  /tmp/makepkg/tensorflow-rocm/src/tensorflow-2.17.0-rocm/WORKSPACE:19:13: in <toplevel>
Repository rule http_archive defined at:
  /home/janluca/.cache/bazel/_bazel_janluca/604c7e0350e7b3b80f4666a83c15fa30/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Skipping '//tensorflow:libtensorflow_framework.so': no such package '@local_config_rocm//rocm': Repository command failed
/opt/rocm/bin/rocm_agent_enumerator:95: SyntaxWarning: invalid escape sequence '\w'
  @staticVars(search_name=re.compile("gfx[0-9a-fA-F]+(:[-+:\w]+)?"))
/opt/rocm/bin/rocm_agent_enumerator:152: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(amdgcn-amd-amdhsa--gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:154: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:175: SyntaxWarning: invalid escape sequence '\w'
  target_search_term = re.compile("1002:\w+")
ERROR: no such package '@local_config_rocm//rocm': Repository command failed
/opt/rocm/bin/rocm_agent_enumerator:95: SyntaxWarning: invalid escape sequence '\w'
  @staticVars(search_name=re.compile("gfx[0-9a-fA-F]+(:[-+:\w]+)?"))
/opt/rocm/bin/rocm_agent_enumerator:152: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(amdgcn-amd-amdhsa--gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:154: SyntaxWarning: invalid escape sequence '\A'
  line_search_term = re.compile("\A\s+Name:\s+(gfx\d+)")
/opt/rocm/bin/rocm_agent_enumerator:175: SyntaxWarning: invalid escape sequence '\w'
  target_search_term = re.compile("1002:\w+")
INFO: Elapsed time: 2.891s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow ... (2 packages)
    Fetching https://storage.googleapis.com/.../archive/11bf7c25e666dd7ddacbcd4d4c4a9de7a25175f8.tar.gz
    Fetching https://github.com/.../rules_cc/archive/624b5d59dfb45672d4239422fa1e3de1822ee110.tar.gz
    Fetching https://github.com/bazelbuild/rules_java/releases/download/5.3.5/rules_java-5.3.5.tar.gz
==> ERROR: A failure occurred in build().
    Aborting...
```
I only found some patches online for rocm-info, none for tensorflow-rocm :(

**Comment by jlo62** [comment]
Found this will be fixed with rocm 6.1.0. guess I'm gonna have to wait till then
